### ISSUE TITLE
Add ability to provide reason when closing connection

### ISSUE THREAD

**Issue by Jahor** [rabbitmq/hop#101]
From API documentation for `DELETE /api/connections/name`:

> Optionally set the "X-Reason" header when DELETEing to provide a reason.

**Comment by michaelklishin** [comment]
This is really straightforward on the surface but actually challenges how we manage headers in the client at the moment. I have a spike that quickly turned into a refactoring of `Client#getRequestFactory` and friends.

I'd like to discuss this with @acogoluegnes and/or @artembilan first.

**Comment by michaelklishin** [comment]
OK, I think I figured DELETE requests with headers out.
