### ISSUE TITLE
Constructing a client with credentials in URL violates assertions

### ISSUE THREAD

**Issue by andreas-schilling** [rabbitmq/hop#108]
Unlike promised through both the API and JavaDoc, constructing a `Client` with just the URL (which then contains the credentials) does not work. The constructor is:

    /**
     * Construct an instance with the provided url and credentials.
     * @param url the url e.g. "http://guest:guest@localhost:15672/api/".
     * @throws MalformedURLException for a badly formed URL.
     * @throws URISyntaxException for a badly formed URL.
    */
    public Client(String url) throws MalformedURLException, URISyntaxException {
        this(url, null, null);
    }

The private constructor which is called in the end then checks these preconditions:

    Assert.notNull(url);
    Assert.notNull(username);
    Assert.notNull(password);
    Assert.notNull(configurator);

**Comment by michaelklishin** [comment]
@andreas-schilling feel free to submit a PR.
