### ISSUE TITLE
Add support for viewing RateDetails sampling data

### ISSUE THREAD

**Issue by mcantrell** [rabbitmq/hop#118]
When supplied with the appropriate query parameters, the queue API will return sampling data. I'd like to request the ability to add these parameters when fetching queue info and model the results from the response:

Command:

      curl -u guest:guest 'http://localhost:15672/api/queues/%2F/foo?lengths_age=60&lengths_incr=5&msg_rates_age=60&msg_rates_incr=5&data_rates_age=60&data_rates_incr=5'

Response (partial):

    "messages_details": {
        "rate": 0.0,
        "samples": [{
            "sample": 0,
            "timestamp": 1511962840000
        }, {
            "sample": 0,
            "timestamp": 1511962835000
        }, {
            "sample": 0,
            "timestamp": 1511962830000
        }, {
            "sample": 0,
            "timestamp": 1511962825000
        }, {
            "sample": 0,
            "timestamp": 1511962820000
        }, {
            "sample": 0,
            "timestamp": 1511962815000
        }, {
            "sample": 0,
            "timestamp": 1511962810000
        }, {
            "sample": 0,
            "timestamp": 1511962805000
        }, {
            "sample": 0,
            "timestamp": 1511962800000
        }, {
            "sample": 0,
            "timestamp": 1511962795000
        }, {
            "sample": 0,
            "timestamp": 1511962790000
        }, {
            "sample": 0,
            "timestamp": 1511962785000
        }, {
            "sample": 0,
            "timestamp": 1511962780000
        }],
        "avg_rate": 0.0,
        "avg": 0.0
    }

**Comment by michaelklishin** [comment]
@dcorbacho @kjnilsson are these samples a part of the public API or just leaked unintentionally?

**Comment by mcantrell** [comment]
Just for reference, I found the info here:

https://cdn.rawgit.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_14/priv/www/doc/stats.html

**Comment by dcorbacho** [comment]
@michaelklishin Those samples are part of the public API, used to generate the graphs in the queue details page.

**Comment by michaelklishin** [comment]
Then we should sketch up what the API for providing custom arguments would look like in Hop.

**Comment by Whitespirit0** [comment]
Hello @michaelklishin, is there any news on this?
I need to add `lengths_age=60&lengths_incr=5` as query parameters and retrieve the `messages_details.avg` field from the response but it doesn't seem possible at the moment.

**Comment by acogoluegnes** [comment]
I confirm this is not available.

From the documentation:
![image](https://user-images.githubusercontent.com/514737/154018437-c833ba45-f4ae-497a-8dd9-ed3bd9ed380e.png)

This targets the `QueueInfo getQueue(String vhost, String name)` method. The `messages_details` property is not available in `QueueInfo`. Quick analysis for the implementation:

 * add a property for `message_details`
 * re-use the `RateDetails` class if possible (used in `MessageStats`)
 * add a `samples` list property in `RateDetails`
 * add a `getQueue` method with a query class to set the query parameters according to the documentation

**Comment by Whitespirit0** [comment]
Thank you for your analysis!

I actually use the `Page<QueueInfo> getQueues(String vhost, QueryParameters queryParameters)` method because I need a name regex and I can confirm that `messages_details` are supported by the API as well in this case.

The following query is what I'm targeting with the Java client:
```
curl -u guest:guest "http://localhost:15672/api/queues/%2F?page=1&page_size=100&name=myPattern&use_regex=true&columns=name,messages_details&lengths_age=60&lengths_incr=5"
```

It seems that `avg` and `avg_rate` would also need to be added to `RateDetails`.

**Comment by acogoluegnes** [comment]
OK, so we would need to add the query parameters data to `getQueues` as well, thanks for the info.

**Comment by Whitespirit0** [comment]
No worries. Any idea of when this could be shipped, even a rough estimate?

**Comment by acogoluegnes** [comment]
Hopefully by March-April 2022, no promises though. Pull requests are always welcome.

**Comment by Whitespirit0** [comment]
Ok thanks. I'll see if I can get around to it at some point.

**Comment by Whitespirit0** [comment]
Thanks @acogoluegnes, that was much quicker than expected! This will be part of the 4.1.0 release, right? Is this release still scheduled for March-April?

**Comment by acogoluegnes** [comment]
There should be a RC next week. In the meantime you can try the snapshot: https://oss.sonatype.org/content/repositories/snapshots/com/rabbitmq/http-client/4.1.0-SNAPSHOT/

Feedback on the API is welcome.

**Comment by Whitespirit0** [comment]
Ok great! I'll be on vacations next week, so I'll test the RC when I come back. But from what I saw, it looks OK to me.

**Comment by Whitespirit0** [comment]
@acogoluegnes, where can I download the RC?

**Comment by acogoluegnes** [comment]
https://github.com/rabbitmq/hop#milestones-and-release-candidates

**Comment by Whitespirit0** [comment]
I've tested the new API and it looks good to me :)
