### ISSUE TITLE
undefined free_disk_limit throws error on getting nodes

### ISSUE THREAD

**Issue by keumda** [rabbitmq/hop#120]
When free_disk_limit is not defined (which is optional as far as I know),
client.getNodes() throws exception below.
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of long from String value ("undefined"): not a valid Long value

Is there any way that I could avoid this issue?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Most installations do not override free disk space limit. See server logs and provide a way to reproduce on the mailing list.

**Comment by michaelklishin** [comment]
[There is a test](https://github.com/rabbitmq/hop/blob/master/src/test/groovy/com/rabbitmq/http/client/ClientSpec.groovy#L104) for `GET /api/nodes` and it is easy to see what's being returned using `curl`:

```
curl -u guest:guest -H "Accept: application/json" -X GET "http://localhost:15672/api/nodes" | python -m json.tool
[
    {
        "cluster_links": [],
        "metrics_gc_queue_length": {
            "channel_closed": 0,
            "channel_consumer_deleted": 0,
            "connection_closed": 0,
            "consumer_deleted": 0,
            "exchange_deleted": 0,
            "node_node_deleted": 0,
            "queue_deleted": 0,
            "vhost_deleted": 0
        },
        "name": "rabbit@warp10",
        "running": true,
        "type": "disc"
    }
]
```
