### ISSUE TITLE
Empty shovel properties corrupts broker

### ISSUE THREAD

**Issue by krm1312** [rabbitmq/hop#138]
`ShovelDetails details = new ShovelDetails(instance.formattedMqUri(), "amqp://", 5, true, Collections.emptyMap());
...
client.declareShovel(vhost, new ShovelInfo(name, details));`

Corrupts broker.  Shovel won't start.  Crashes at startup.

`ShovelDetails details = new ShovelDetails(instance.formattedMqUri(), "amqp://", 5, true, null);
...
client.declareShovel(vhost, new ShovelInfo(name, details));`

An empty map for publish-properties is what causes it.  null is ok.

rabbit 3.7.5/Erlang 20.3.5

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
I'm not sure what Hop can do other than throw an illegal argument exception. I don't see why RabbitMQ wouldn't be able to start with a set of publish properties that causes individual Shovels to fail.

This is mailing list material at this point.

**Comment by michaelklishin** [comment]
With 3.7.9 I can reproduce an exception in the dynamic Shovel startup and a 500 response from the HTTP API declaration but the broker does restart successfully and I don't see why it wouldn't since dynamic Shovels are not a part of the core and do not prevent any plugins from starting.

I will file two more specific issues.
