### ISSUE TITLE
Support for all dynamic shovel properties

### ISSUE THREAD

**Issue by mhewedy** [rabbitmq/hop#143]
The `com.rabbitmq.http.client.domain.ShovelDetails` lacks most of the  [dynamic shovel properties](https://www.rabbitmq.com/shovel-dynamic.html).  Like the ability to auto-delete the shovel using `src-delete-after`.

As I workaround, I created a subclass for `ShovelDetails` object and added the properties I needed.

It should be nice if we can configure the complete list of the properties out-of-the-box.

**Comment by mhewedy** [comment]
I like the idea ...  I will prepare the PR soon

**Comment by michaelklishin** [comment]
Addressed by #144.
