### ISSUE TITLE
Use better variable name for last parameter in "com.rabbitmq.http.client.Client.unbindQueue(String, String, String, String)" method

### ISSUE THREAD

**Issue by asdf913** [rabbitmq/hop#177]
According to the HTTP API documentation page, the last parameter in URL is **prop**
![image](https://user-images.githubusercontent.com/2301325/57066225-38167680-6cfe-11e9-8367-ac07189f9690.png)

The **prop** is the value of the method parameter **routingKey**
com.rabbitmq.http.client.Client.unbindQueue(String, String, String, String)
![image](https://user-images.githubusercontent.com/2301325/57066271-58decc00-6cfe-11e9-9313-49f283732380.png)

The method parameter **routingKey** is misleading (i.e. not match the HTTP API documentation page).
The parameter is suggested to renamed to **propertiesKey** (aligned to the HTTP API documentation page)

**Comment by michaelklishin** [comment]
There is no such thing as "properties key". It is a map of properties in the API, of which routing key is very often the only argument (but there can be more with custom exchange types). Hop therefore is simply provides a shortcut that does not require the user to provide a map with a single key.

**Comment by asdf913** [comment]
Thank you for your prompt response.
I would like to suggest that adding java docs to explain the usage of the method Client.
Java docs could help programmer how to use the method properly.

**Comment by michaelklishin** [comment]
I will look into that.

**Comment by asdf913** [comment]
Thanks you for your work.
