### ISSUE TITLE
HTTP proxy settings

### ISSUE THREAD

**Issue by markw83** [rabbitmq/hop#178]
I try to access the RabbitMQ API via a proxy. Therefore, I would need to set the proxy settings to the http client of the library. But I am unable to find out how to configure it. Normally (as I understood) it would be enough to tell the http client builder to useSystemProperties to handle http.proxyHost, http.proxyPort, https.proxyHost, https.proxyPort and http.nonProxyHosts automatically.

Is there a way to tell the client to use the proxy or can this be implemented in the near future?

**Comment by michaelklishin** [comment]
This is open source software. You are welcome to contribute HTTP proxy support.

**Comment by acogoluegnes** [comment]
This should be possible by tweaking the `HttpClient` with the `HttpClientBuilderConfigurator`. You mentioned the `HttpClientBuilder#useSystemProperties` method, have you tried this with setting the appropriate system properties?

System properties affect the whole JVM process, so you may try a couple of other solutions: `HttpClientBuilder#setProxy` or `HttpClientBuilder#setRoutePlanner` with a `DefaultProxyRoutePlanner` instance. The latter solution is mentioned in the [RestTemplate documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-http-clients.html#howto-http-clients-proxy-configuration) (which HOP using under the covers), so hopefully it should work.

Your feedback is welcome, so we can update the readme with the working solution.

**Comment by markw83** [comment]
Thank you for your responses. I tested it by making a copy of the Client and added the useSystemProperties flag to the HttpClientBuilder. It seems to work fine. In our case we have the configuration in the JVM via the system properties, therefore, this would be the best solution for us.

Maybe the code can be extended to have the possibility to add additional parameter, e.g, for proxy settings, a route planner and to enable the usage of system properties.

The rest template customization updates all rest templates as far as I understood. As in our case there are more rest templates where some should not use a proxy, I guess this solution may not be best for us.

**Comment by acogoluegnes** [comment]
There's no need to copy the class, use a [constructor with a `HttpClientBuilderConfigurator` parameter](https://github.com/rabbitmq/hop/blob/5c0420f8929186952338d38057cb65092ef36f9a/src/main/java/com/rabbitmq/http/client/Client.java#L114), it's a callback to customize the `HttpClientBuilder`, e.g.:

```java
Client client = new Client(url, username, password, 
  (HttpClientBuilderConfigurator) builder -> builder.useSystemProperties());
```

**Comment by markw83** [comment]
Thank you for pointing me do this possibility. I now have the problem, that we have SSL and therefore, providing the SSL context but there is no constructor allowing SSL  and the configurator. Thus, either I have the system properties or SSL but not both. Checking the code, when using SSL always the NO_OP_HTTP_CLIENT_BUILDER_CONFIGURATOR is used.

Thus, would we need a constructor supporting all flags that also the getRequestFactory allows?

**Comment by acogoluegnes** [comment]
The `SSLConnectionSocketFactory` and `SSLContext` are passed in to the `HttpClientBuilder`, so you can do the same in the `HttpClientBuilderConfigurator` and use the constructor with the `HttpClientBuilderConfigurator` argument.

**Comment by markw83** [comment]
Thanks, this worked fine for me. I only found an issue with the handling of the different constructors. Using the constructor with SSL parameters checks the rootUri and attaches (if necessary) a / and the a toUri (lines 160 - 164). The constructor called by the configurator does only perform a toUri (line 227).

This results in an 406 Not acceptable error. Adding the / to the request uri before calling RabbitMQ, works fine. I would suggest to harmonize the handling of the rootUri in the two constructors.

**Comment by michaelklishin** [comment]
I would be much easier to proceed if instead of prose referencing line numbers we had an executable code example.

**Comment by markw83** [comment]
Sorry, the constructor I mentioned looks currenlty like the following:

    private Client(URL url, String username, String password, SSLConnectionSocketFactory sslConnectionSocketFactory,
                 SSLContext sslContext,
                 HttpClientBuilderConfigurator configurator) throws URISyntaxException, MalformedURLException {
        Assert.notNull(url, "URL is required; it must not be null");
        Assert.notNull(username, "username is required; it must not be null");
        Assert.notNull(password, "password is required; it must not be null");
        Assert.notNull(configurator, "configurator is required; it must not be null");
        this.rootUri = url.toURI();

        HttpComponentsClientHttpRequestFactory rf = getRequestFactory(url, username, password,
            sslConnectionSocketFactory, sslContext, configurator);
        this.rt = new RestTemplate(rf);
        this.rt.setMessageConverters(getMessageConverters());
    }

I think it should be:

    private Client(URL url, String username, String password, SSLConnectionSocketFactory sslConnectionSocketFactory,
                 SSLContext sslContext,
                 HttpClientBuilderConfigurator configurator) throws URISyntaxException, MalformedURLException {
        Assert.notNull(url, "URL is required; it must not be null");
        Assert.notNull(username, "username is required; it must not be null");
        Assert.notNull(password, "password is required; it must not be null");
        Assert.notNull(configurator, "configurator is required; it must not be null");
        if (url.toString().endsWith("/")) {
            this.rootUri = url.toURI();
        } else {
            this.rootUri = new URL(url.toString() + "/").toURI();
        }

        HttpComponentsClientHttpRequestFactory rf = getRequestFactory(url, username, password,
            sslConnectionSocketFactory, sslContext, configurator);
        this.rt = new RestTemplate(rf);
        this.rt.setMessageConverters(getMessageConverters());
    }

**Comment by acogoluegnes** [comment]
OK, thanks for reporting this, I created a follow-up issue #179. I'm closing now this issue, please move conversation like this one to the [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) in the future. Thanks.
