### ISSUE TITLE
ShovelDetails doesn't support multiple uris for source and destination

### ISSUE THREAD

**Issue by Haster2004** [rabbitmq/hop#192]
Hi guys!
In rabbitmq shovel plugin it is allowed to setup multiple uris for src-uri and dest-uri.
But ShovelDetails doesn't allow to setup multiple uris:
In ShivelDetails.java:

``` java
	@JsonProperty("src-uri")
	private String sourceURI;
```

But should be

``` java
	@JsonProperty("src-uri")
	private List<String> sourceURI;
```

**Comment by michaelklishin** [comment]
@Haster2004 are you sure your suggested change would be backwards compatible? If so we'd consider a pull request.

**Comment by Haster2004** [comment]
@michaelklishin 
My suggestion is:
1) sourceURi and destinationUri define like this:
	@JsonProperty("src-uri")
	@JsonFormat(with = {ACCEPT_SINGLE_VALUE_AS_ARRAY, WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED})
	private List<String> sourceURI = new ArrayList<>();

It will allow to serialize one-element arrays like string and deserialize strings like one-element arrays/

2) Memodes getSourceURI, setSourceURI, getDestinationURI and setDestinationURI annotate with @Deprecated and implement to put value in array or get first value of array

	@Deprecated
	public String getSourceURI() {
		return sourceURI.get(0);
	}

	@Deprecated
	public void setSourceURI(String sourceURI) {
		this.sourceURI.clear();
		this.sourceURI.add(sourceURI);
	}
3) Add new methods with s on the end: 
List<String> getSourceURIs()
setSourceURIs(List<String>)
...

**Comment by acogoluegnes** [comment]
This looks reasonable to me.

**Comment by michaelklishin** [comment]
@Haster2004 would you be interested in submitting a pull request?

**Comment by Haster2004** [comment]
@michaelklishin yes, on weekend I'll try to submit a pull request
