### ISSUE TITLE
how to run tests ?

### ISSUE THREAD

**Issue by asomov** [rabbitmq/hop#198]
I wanted to contribute but I do not get how to run the tests.
` ./gradlew clean test` fails:

```Running test "Test GET /api/overview(com.rabbitmq.http.client.ClientSpec)"

com.rabbitmq.http.client.ClientSpec > GET /api/overview FAILED
    java.net.ConnectException at ClientSpec.groovy:2095
Running test "Test user info decoding(com.rabbitmq.http.client.ClientSpec)"
Running test "Test GET /api/nodes(com.rabbitmq.http.client.ClientSpec)"
Running test "Test GET /api/nodes with a user-provided HTTP builder configurator(com.rabbitmq.http.client.ClientSpec)"
Running test "Test GET /api/nodes with credentials in the URL(com.rabbitmq.http.client.ClientSpec)"
```

Unfortunately the line number does not give any indication where the test fails.

I have tried to change the URL of RabbitMQ (to point to RabbitMQ running in docker):
new Client("http://localhost:8080/api/", DEFAULT_USERNAME, DEFAULT_PASSWORD)

but it does not help.

What should I do to run the tests ?

**Comment by michaelklishin** [comment]
[See .travis.yml](https://github.com/rabbitmq/hop/blob/master/.travis.yml).

**Comment by michaelklishin** [comment]
The README section of [Running Tests](https://github.com/rabbitmq/hop/blob/master/README.md#running-tests) now explains how to set up the node and/or run the suite against a  local RabbitMQ installation that's not in `PATH`.

**Comment by michaelklishin** [comment]
If you want to run the tests against a node running in a container you have to forward local port `15672` to the container's port `15672`. RabbitMQ HTTP API does not use port `8080`. There is no way to override the endpoint used. @acogoluegnes maybe that's something worth doing?

**Comment by asomov** [comment]
Thank you.

**Comment by acogoluegnes** [comment]
@michaelklishin Sure, it's possible, I'll do it.
