### ISSUE TITLE
POST /api/queues/{vhost}/{name}/get backwards compability with older RabbitMQs

### ISSUE THREAD

**Issue by biniosuaf** [rabbitmq/hop#203]
Hey, thanks for a very handy project! Top work! 
I'm trying to implement it in our test frameworks. It turned out some of our environments use the older RabbitMQ 3.6.1. I noticed a difference in the body in this POST request varying in >3.6.* and 3.7.* onward versions of Rabbit:

3.6.* payload (old):
```
 {
"count":5,
"requeue":true,
"encoding":"auto",
"truncate":50000
}
```

3.7.* payload (new):
```
 {
"count":5,
"ackmode":"reject_requeue_false",
"encoding":"auto",
"truncate":50000
}
```

Do you plan any support for the old RMQ version specifically in that endpoint?
I figured out a very fast and simple solution (see PR) which sends both fields in the body and works with both new and old API at the same time.

PR: https://github.com/rabbitmq/hop/pull/202/files

**Comment by michaelklishin** [comment]
RabbitMQ 3.6 has been [out of support](https://www.rabbitmq.com/versions.html) for 18 months now. Sorry, but we don't support it anymore. You have to use an older version of Hop or better yet, don't consume over HTTP API.
