### ISSUE TITLE
Support for different httpclients to apache http-client

### ISSUE THREAD

**Issue by kubamarchwicki** [rabbitmq/hop#205]
`hop` is currently using `apache httpclient` as the default implementation for handling HTTP traffic. However, as it uses `RestTemplate` as the main abstraction, it's possible to add other transport libraries (like okhttp) in a transparent manner.

## Rationale
When using `hop` in different environments, the choice of actual http client is usually opinionated and followed by a set of configurations and metrics. Adding `httpclient` together with `hop` may require (for example) an additional level explicit of configuration. I strongly believe a choice of the underlying http client should be transparent for a utility library like `hop`.

**Comment by kubamarchwicki** [comment]
I've drafted a backwards compatible change in here https://github.com/rabbitmq/hop/compare/master...kubamarchwicki:okhttpclient-support?expand=1 and would be keen on understanding if that's something interesting from `hop` perspective. We started using it internally as our microservice infrastructure relies heavily on `okhttp` and we simply know it better :)

**Comment by acogoluegnes** [comment]
This is something we can consider if it does not break the current implementation. I'll have a look at it tomorrow.

**Comment by acogoluegnes** [comment]
This looks good. A couple of remarks though.

I think we should not deprecate the historical constructors as this means they should be removed in the next major release, leaving the user with a technical choice (choosing Commons HTTP or okhttp) that they did not ask for. People have been fine with Commons HTTP for years, so it can stay the default.

We can do better on the naming, there are `Configurator`s, `Configurer`s, this needs consistency.

I'll work on this.

Thanks for the contribution!

**Comment by kubamarchwicki** [comment]
Thank you for feedback. I was trying to be least invasive possible (with regards to the existing codebase) - still providing the flexibility of choosing transport layer. Shall I open a PR or leave it as it is?

**Comment by acogoluegnes** [comment]
No worries, I already created a [PR from your branch](https://github.com/rabbitmq/hop/pull/206) and I'm currently working on it!

**Comment by acogoluegnes** [comment]
@kubamarchwicki I opened a [follow-up PR](https://github.com/rabbitmq/hop/pull/207) and did some refactoring (see the [commit message](https://github.com/rabbitmq/hop/pull/207/commits/89cdeac02f22b94ec7ec76dcbd47145318419938) for more information). Feedback is welcome.
