### ISSUE TITLE
POST /api/exchanges/{vhost}/{name}/publish

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/hop#21]

**Comment by ikuznechikova** [comment]
:) Hello!  Should we hope that this will be realized in the very near future?

**Comment by michaelklishin** [comment]
@ikuznechikova sorry but that's not how open source works. You don't get things done by asking others to do them.

Hop is pretty feature complete so there is a chance that we will get to this endpoint soon but I'd recommend not counting on it unless you contribute and how using HTTP API for publishing either way. The HTTP API is not meant to be used for messaging, only monitoring. Publishing and consumption over it should be considered last resort kind of measures. Which means this endpoint is a lot less interesting than it seems.

I'd personally [cover over a dozen of other endpoints Hop does not yet support](https://github.com/rabbitmq/hop/issues) over this one but perhaps @acogoluegnes feels differently.

**Comment by acogoluegnes** [comment]
Indeed publishing from the HTTP API is far from optimal. @ikuznechikova Could you tell us more about your use case?

**Comment by biniosuaf** [comment]
Similarly for me. Integration tests use case.
