### ISSUE TITLE
Expose Client internals (restTemplate, uri) for an easier extension

### ISSUE THREAD

**Issue by kubamarchwicki** [rabbitmq/hop#215]
RabbitMQ http API changed a bit over time and http client is not backwards compatible. While I completely understand not focusing on supporting legacy versions of RabbitMQ (like 3.6), the current structure of the `Client` class does not allow extensions, in order to provide an inhouse implementation of single features of RabbitMQ. 

## Proposal
Provide access to the `Client`'s attributes (https://github.com/rabbitmq/hop/blob/master/src/main/java/com/rabbitmq/http/client/Client.java#L47-L48) to allow class extensions (composition) in order to support other (legacy) versions of broker API.

## Rationale
The API I'm having in mind is dynamic shovels, which http API changed between versions 3.6.x and 3.7 of rabbit (yes, I know it reached it's EOF 2 years ago - but some people still use it). 

The 3.6 API to create a shovel

```json
{
  "name":"shovelName",
  "value":{
    "src-uri":"amqp:///%2f",
    "src-queue":"some-source-queue",
    "dest-uri":"amqp:///%2f",
    "dest-queue":"some-destination-queue",
    "delete-after": "queue-length"
  }
}
```

The 3.7+ API to create a shovel (currently supported by the the `http-client`)

```json
{
  "name":"shovelName",
  "value":{
    "src-uri":"amqp:///%2f",
    "src-queue":"some-source-queue",
    "src-dest-queue":"some-destination-queue",
    "dest-uri":"amqp:///%2f",
    "delete-after": "queue-length"
  }
}
```

The current implementation does not allow building a different implementation of client methods (unless some reflections hack). To address it, I can think about two approaches: making the fields protected (giving access in subclasses) or provide accessor methods which will handle a cloned object (URI is immutable, but the RestTemplate isn't). 

That will allow targeting the differences between the rabbit APIs in a non-invasive way.

**Comment by michaelklishin** [comment]
Making client fields protected sounds good to me. Please submit a PR.
