### ISSUE TITLE
Provide a support for delete queue query parameters

### ISSUE THREAD

**Issue by kubamarchwicki** [rabbitmq/hop#217]
The RabbitMQ HTTP API support additional query parameters when deleting a queue. The `http-client` currently doesn't support it

> When DELETEing a queue you can add the query string parameters `if-empty=true` and / or `if-unused=true`. These prevent the delete from succeeding if the queue contains messages, or has consumers, respectively

I'll work on that PR

**Comment by kubamarchwicki** [comment]
That would fix (or open a way to support) #118, isn't it?

**Comment by michaelklishin** [comment]
#118 may depend on query parameters but is otherwise not really connected. Why?

**Comment by kubamarchwicki** [comment]
I was referring to the query parameters aspect. Sorry if that brought some confusion :)

To my understanding of the codebase, the query parameters are not really used so far in the `http-client` (or at least I haven't found anything). There is no convention for the model (`ShovelInfo`, `QueueInfo` and other `*Info` classes are used to pass http body details. The `*Details` classes encapsulate the response data. The are not model classes for query parameters). Additionally, the rest template configuration (I started with the synchronous client) handles path segments and not query parameters. 
Building a convention in one of these two changes - will make the other a fairly trivial change.

**Comment by michaelklishin** [comment]
That's a fair analysis.

**Comment by acogoluegnes** [comment]
I would add a new `deleteQueue(String vhost, String name, DeleteQueueParameters parameters)` method with the 2 flags as properties. The parameters would be added to the URL if they're present and the `RestTemplate` would encode the values with one of the [`delete`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html#delete-java.lang.String-java.util.Map-) [methods](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html#delete-java.lang.String-java.lang.Object...-) that accept parameters.

**Comment by kubamarchwicki** [comment]
Thank you @acogoluegnes  - that's exactly how I started. I'll amend the naming and provide a test accordingly :-)
