### ISSUE TITLE
Move build to Maven

### ISSUE THREAD

**Issue by lukebakken** [rabbitmq/hop#225]
PT issue #169917951

Gradle has been more of a hassle than bringing benefits. Hop remains a simple project with simple needs and Maven should be more than enough.

**Comment by lukebakken** [comment]
@acogoluegnes originally opened the issue in tracker so I'll let him weigh in :smile:

**Comment by acogoluegnes** [comment]
Some reasons:
 * Gradle upgrades can be be painful, finding the new Groovy-DSL incantation to do the exact thing as in a previous version can be incredibly frustrating and time-consuming (for absolutely no added-value most of the time).
 * Gradle is always lagging to support the [latest versions of Java](https://github.com/gradle/gradle/issues/10248). With the 6-month release cycle Java recently adopted, Gradle lag makes it very difficult or even impossible to test projects on a new Java version before it is released or even after! All our Java libraries are continuously tested against the available Java versions (from 8 to 16 currently) and I had to generate a Maven project on-the-fly with the Gradle Maven plugin to launch Hop test suite with Maven against Java versions that Gradle does not support.
 * All our Java libraries are using Maven already (and are fine with it).
 * The IDE support for Gradle is buggy, it became impossible to run tests in IDEA a while ago, no idea why. Does not happen with Maven.
 * The release process is currently using the Spring team infrastructure (this is historical). This process is mostly manual, long, and error-prone. We could use our CI to automatize it, just like for our other Java libraries, but this means doing more Gradle configuration incantation, dealing with upgrades every time the Gradle team feels like breaking existing configuration files, and creating new CI pipelines to release a Gradle project. With Hop as a Maven project, we can just re-use our existing pipelines.

I don't bear a grudge against Gradle, it's just I don't feel a library like Hop requires it. Hop will need much less massaging when it will be a Maven project.
