### ISSUE TITLE
QueueInfo class content confusion

### ISSUE THREAD

**Issue by zhuangzhuangdashen** [rabbitmq/hop#226]
i saw "  // TODO: recoverable_slaves " this in QueueInfo class ,why deliberately dismiss it?when will open it?

**Comment by michaelklishin** [comment]
A `TODO` is a `TODO`. It is not "deliberately omitted", just not a particularly useful property that is not present in many cases and no one has asked for so far. And quorum queues don't have an equivalent at all.

It will be included when someone contributes support for it but I'm not sure it's worth including at all.
