### ISSUE TITLE
Alias for classic mirrored queue pids field

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/hop#227]
Classic mirrored queues have originally used an unfortunate term, "slave", to refer to secondary replicas. We have eradicated this from the docs years ago but it is still a field served by the HTTP API and displayed/accepted by CLI tools.

Given a broad range of tools that use both, renaming it would be a significant breaking change. However, we can and should give those who do not want to refer to that field in their own applications, tools or command line usage an option.

For example, we can alias `slave_pids` as `mirror_pids` in CLI tools, their underlying internal API responses and HTTP API responses. This won't break any existing tooling but will give the community an option of using a non-controversial field name.

In the long term we expect classic mirrored queues to be deprecated and removed, which would make the field go away for good.

**Comment by acogoluegnes** [comment]
@michaelklishin I cannot find a reference to `slave` anywhere in the code, so I guess this field has never been mapped. Should we consider closing this issue?

**Comment by michaelklishin** [comment]
The word appears in HTTP API responses, at least for classic mirrored queues. We have to support both fields so that we can eventually rename or alias them in the HTTP API. This would at least give the user a chance to avoid having the s-word used in their own code.

**Comment by acogoluegnes** [comment]
I understand, but it seems this particular field from the HTTP API has never been mapped in HOP so far, so I thought this issue was about adding a new Java property, e.g. `mirrorPids`, mapped with the `slave_pids` JSON field, and deprecate some existing `slavePids` Java property.

So maybe it is more about  adding `mirrorPids` now to avoid adding a `slavePids` by mistake later?

**Comment by michaelklishin** [comment]
Ah, great, then we can start with a sensible value. Can Jackson handle two fields mapping to a single field in an OR manner?

**Comment by acogoluegnes** [comment]
I don't know, I can check this out while adding the `mirrorPids` property.

**Comment by acogoluegnes** [comment]
After some investigation, the `JsonAlias` annotation should to the trick to map several JSON fields to the same Java property if the HTTP API changes.
