### ISSUE TITLE
Connection Details from Spring AMQP?

### ISSUE THREAD

**Issue by lost-carrier** [rabbitmq/hop#239]
Maybe I'm just missing a bit of documentation here, but - since this is recommended by Spring AMQP project:

What is the most elegant way to ome from a Spring AMQP wired connection (-> `RabbitTemplate`) to a HOP one?

The Spring AMQP `ConnectionFactory` or `Connection` would offer host, post, virtualHost, username, but NO password. The thing is that I might not actually know where Spring is getting the connection details from (imagine Docker or CloudFoundry context). There is not by chance anything like `Client hopClient = new Client(rabbitTemplate.getConnectionFactory());`? (...at least I could not find anything useful...)

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
