### ISSUE TITLE
getConsumers with QueryParameters

### ISSUE THREAD

**Issue by mheidt** [rabbitmq/hop#247]
Gladly I found the missing getConsumers in the latest release.
Could you please add the one that takes QueryParameters as Parameter as well, so that I can filter by name and regexp?

Cheers,
Markus

**Comment by acogoluegnes** [comment]
The consumers endpoint does not support pagination and I don't think it supports filtering by name/regex.

**Comment by mheidt** [comment]
@michaelklishin
It seems, that we have a major issue with this call.
Our productive rabbit has a shovel defined and those connections look like
{
    "arguments": {},
    "ack_required": true,
    "active": true,
    "activity_status": "up",
    "channel_details": {
      "connection_name": "<rabbit@10-244-108-91.1628951087.17337.1>",
      "name": "<rabbit@10-244-108-91.1628951087.17337.1> (1)",
      "node": "rabbit@10-244-108-91",
      "number": 1,
      "peer_host": "undefined",
      **"peer_port": "undefined",**
      "user": "shovel"
    },
    "consumer_tag": "amq.ctag-uLSmF70x9pQEDL34OCbkvg",
    "exclusive": false,
    "prefetch_count": 1000,
    "queue": {
      "name": "amq.gen-vIuezFJTmuEAOB2SouuafQ",
      "vhost": "PROD"
    }
  },

The peer_port yields to
JSON parse error: Cannot deserialize value of type `int` from String "undefined": not a valid Integer value;

Should I make a PR, that is making ChannelDetails.peerPort a String?

**Comment by mheidt** [comment]
Of course nicer would be if the API (not hop) would support the filter...

**Comment by Guzzi** [comment]
@michaelklishin: Alternatively (and not breaking the http API) it might be possible to fix this in the shovel plugin, so that either a real portnumber or "0" is set for unknown port in peer_port !?

**Comment by acogoluegnes** [comment]
The management API should fix the issue, maybe a proper default value would be 0 or -1, I don't know if this happens in other cases. It's also weird the values are not set.

This should also be fixed in Hop, in case the client is used with broker versions without the fix. I'd say the simplest is to use a custom deserializer that handles the `undefined` value. We cannot change the type, it would be a breaking change.

**Comment by acogoluegnes** [comment]
Closed in favor of #248.
