### ISSUE TITLE
Provide more information in case of error

### ISSUE THREAD

**Issue by Whitespirit0** [rabbitmq/hop#271]
Hello,

From the few tests I've done, it seems that the blocking IO client does not give access to much information in case of error (haven't tried other clients because I need the blocking one). It actually took me quite some time to figure out that I had a password problem.

Calling the `getQueue(s)` methods with a wrong password or with a non-existing queue either gives a cryptic Jackson parsing error or simply returns `null`.

As a user of the client, I would be interested in having a way to get the HTTP status code and raw (unparsed) response body in case of error.
As an example, here is the exception that is thrown by API calls for the Kubernetes Java client : [ApiException.java](https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiException.java).

What do you think about this?

**Comment by michaelklishin** [comment]
Server logs would contain a very specific message when authentication fails.

Since every response in theory has access to the HTTP context, changing the API to include it makes some sense.
How many changes this would require given a specific HTTP client, I cannot immediately tell.

**Comment by acogoluegnes** [comment]
I'll give a try because it's easy to test, but more information would be welcome: Hop version, a code snippet to reproduce (to find out which HTTP layer is used). Without this it's difficult to diagnose the problem. Thanks.

**Comment by acogoluegnes** [comment]
The (default) `HttpClient` layer introduced in 4.0 would not handle errors properly for GET requests, I pushed a couple of changes to fix this. This is likely what you're were experiencing, but I'll wait your confirmation before releasing 4.1.

**Comment by Whitespirit0** [comment]
Thanks for your reply and fixes. I'll get back to you next week.

**Comment by Whitespirit0** [comment]
Ok I see, well it's not a big deal but something to be aware of to avoid `NullPointerException`s.
