### ISSUE TITLE
PUT /api/global-parameters/{name} 

### ISSUE THREAD

**Issue by awills96** [rabbitmq/hop#426]
### Is your feature request related to a problem? Please describe.

There is currently no functionality to modify global parameters using the Hop client.

### Describe the solution you'd like

An implemented function in `Client.java` to make api PUT requests for global parameter values.

### Additional context

I saw that https://github.com/rabbitmq/hop/issues/62 has been open for vhost parameters, but there is no mention of global parameter setting in any other issue or discussion that I have seen (besides the latest version release which adds globals to `Definitions.java`). 

I am able to make a contribution, but due to the existing related issue and the relative complexity of the solution, I wanted to check if there are any considerations from the maintainers of this project.

**Comment by michaelklishin** [comment]
It should be a matter of replicating the existing API for parameters without the virtual host argument. We'd appreciate a contribution :)

**Comment by awills96** [comment]
Thank you for the quick response, hopefully I'll have a contribution PR sometime next week or so.

**Comment by michaelklishin** [comment]
@awills96 we can use generics of it improves something… global parameter values really can be anything, so not a lot of room for additional type safety.

As for `mqtt_port_to_vhost_mapping`, it does not use any "MQTT calls", it is just a specific way of setting one specific parameter. It can be a separate method that relies on a more generic one, or it can use the HTTP API client directly, whichever option looks simpler overall.

**Comment by michaelklishin** [comment]
Addressed by @awills96 in https://github.com/rabbitmq/hop/pull/429. Thank you!

**Comment by acogoluegnes** [comment]
Addressed partly in #429 (support for `mqtt_port_to_vhost_mapping`, but not for any global parameter).
