### ISSUE TITLE
Add activity_status attribute to ConsumerDetails

### ISSUE THREAD

**Issue by mikymigs** [rabbitmq/hop#470]
### Is your feature request related to a problem? Please describe.

`ConsumerDetails` class does not map the activity_status attribute of the `/api/consumers` response.

### Describe the solution you'd like

The `/api/consumers` call provides a list of consumers. Each consumer object in the response has an `activity_status` attribute that can have values such as `waiting` or `single_active`. I would like it if you could add this field to the `ConsumerDetails` class.

Other fields are missing such as `ack_required` or `consumer_timeout`.  I don't necessarily need those but I don't see any reason why the lib should limit the information available via the management API (might as well build our own lib in this case...)

Thanks a lot,

### Describe alternatives you've considered

Using the `active` flag but it doesn't provide enough details.

**Comment by michaelklishin** [comment]
@mikymigs you are welcome to contribute it. It should be a matter of a [Jackson mapping change](https://github.com/rabbitmq/hop/blob/main/src/main/java/com/rabbitmq/http/client/domain/ConsumerDetails.java#L27).

Adding a test should be reasonably straightforward, too, but if it's a matter of adding one field to an existing domain class, I'd personally accept a PR without any tests.

**Comment by mikymigs** [comment]
Thank you for your reply @michaelklishin 
Would be happy to contribute. I will try to propose a PR when I find the time :)

**Comment by mikymigs** [comment]
Hello @michaelklishin,
Tried to push a branch it seems I don't have access rights. Can you authorize me to push branches and create PRs ?

Thanks

**Comment by michaelklishin** [comment]
@mikymigs of course not. You need to [fork this repo](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo), push a branch to your own fork and then [submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by mikymigs** [comment]
Sorry, new to the github practices. Will go through a fork.

**Comment by acogoluegnes** [comment]
Fixed in #471.
