### ISSUE TITLE
GitHub release missing for 5.3.0

### ISSUE THREAD

**Issue by der-eismann** [rabbitmq/hop#508]
### Describe the bug

Hey everyone! I know it's only been 3 days since 5.3.0 was tagged, however the releases for 5.2.0 and 5.1.0 were created on the same day as the Git tag, so I was wondering if it was just forgotten. Would you be so kind to create a release with changelog for 5.3.0 as well? Thank you very much!

### Reproduction steps

1. [See 5.3.0 in tags](https://github.com/rabbitmq/hop/tags)
2. [No 5.3.0 in releases](https://github.com/rabbitmq/hop/releases)

### Expected behavior

Release with changelog on the same day as Git tag

**Comment by acogoluegnes** [comment]
I created the tag and published the artifacts last Friday but created the release this morning. I usually do it at the same time but got caught up with other things on Friday, sorry for the delay  :-)
