### ISSUE TITLE
QueueInfo should check for owner_pid_details when determining exclusivity

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/hop#74]
Exclusive queues are currently indicated via non-blank `owner_pid_details` in the payload. That's internal implementation details leaked and has been that way for a while.

While RabbitMQ management API should definitely include a field for `exclusive`, to have to work around this in the clients in order to be compatible with existing versions.

**Comment by michaelklishin** [comment]
`rabbitmq-management` issue: https://github.com/rabbitmq/rabbitmq-management/issues/40.

**Comment by Gsantomaggio** [comment]
I think this issue can be closed.

I tested this code:

    .....
    Channel channel = connection.createChannel();
    String queueName = channel.queueDeclare().getQueue();
    .....
    Client client_http = new Client("http://127.0.0.1:15672/api/", "guest", "guest");
    for (QueueInfo queueInfo : client_http.getQueues()) {
     System.out.println(queueInfo);
    }

Using Master version  (OK):

    QueueInfo{vhost='/', name='amq.gen-uoIFfxJxxwBrkRqRX8qnEQ', durable=false, exclusive=true, autoDelete=true ..}

And Version 3.5.4 (Not OK):

    QueueInfo{vhost='/', 
    name='amq.gen-g3OV8WAOkMJ8_EU6ZR91Ig', 
    durable=false, exclusive=false, autoDelete=true...}

**Comment by michaelklishin** [comment]
We can't close this because 3.6.0 isn't out yet and won't be the minimum version HTTP API clients support for a long time.

**Comment by michaelklishin** [comment]
Fixed by Sam Ryan during a pairing session.
