### ISSUE TITLE
com.rabbitmq.http.client.domain.ClientProperties add "connection_name"

### ISSUE THREAD

**Issue by artembilan** [rabbitmq/hop#84]
The raw API returns normal JSON with the:
```
,"client_properties":
           {"connection_name":"class org.springframework.amqp.rabbit.connection.CachingConnectionFactory#0",
            "product":"RabbitMQ","copyright":"Copyright (c) 2007-2016 Pivotal Software,  Inc.",
            "capabilities": ...
```

Add the `connection_name` property to the `ClientProperties` for more coverage.

**Comment by artembilan** [comment]
On the other hand `getConnection(String name)` doesn't look pretty nice, too.
The `name` in my case is like:
```
"node":"rabbit@HOME","name":"127.0.0.1:57446 -> 127.0.0.1:5672","port":5672,
```
Which isn't human-friendly...

**Comment by michaelklishin** [comment]
@artembilan so you would like to have a connection name in client properties? It should be returned as long as it was provided by the client. Or perhaps I'm misunderstanding what this issue is about :)

**Comment by artembilan** [comment]
Right, that is returned. But since we request to map that JSON to the `ClientProperties`, we just bypass those properties which are not present in the `ClientProperties`: 
```
public class ClientProperties {
  private Map<String, Object> capabilities;
  private String product;
  private String platform;
  private String version;
  private String information;
  private String copyright;
```
