### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/hop#91]
We haven't had a release in over a year.

**Comment by artembilan** [comment]
Fine with me. Will do over a couple days

**Comment by artembilan** [comment]
@michaelklishin , just for an accuracy.
Are we really talking about `1.1.0`, not `1.0.1` like we currently use in Spring AMQP?

IMO, I'm fine with `1.1.0`. That really was a long time do not release anything...
Plus with such a jump we can upgrade a lot of dependencies to their latest versions.

Thanks

**Comment by michaelklishin** [comment]
@artembilan yes, I had a `1.1.0` in mind. Feel free to upgrade the dependencies as you see fit. There has been enough changes to warrant a `1.1.0` even if we didn't want to do that or include new public API elements such as #90.

**Comment by artembilan** [comment]
Please, no commits to master.
I'm starting release for `1.1.0`...

**Comment by michaelklishin** [comment]
Yup, not merging or pushing anything else for the next day :)

**Comment by artembilan** [comment]
Fixed https://bintray.com/spring/jars/com.rabbitmq/1.1.0.RELEASE.
Will be in Maven Central over several hours.

/CC @alenkacz
