### ISSUE TITLE
`gradle check` is a no-op unless `gradle check` is performed

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/hop#93]
Compare the two `gradle check` runs:

```
λ ~/Development/RabbitMQ/hop.git/ master gradle clean
:clean

BUILD SUCCESSFUL

Total time: 0.888 secs
λ ~/Development/RabbitMQ/hop.git/ master gradle check
:compileJava
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
objc[73034]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java (0x10b7034c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10b7cb4e0). One of the two will be used. Which one is undefined.
:check

BUILD SUCCESSFUL

Total time: 12.154 secs
λ ~/Development/RabbitMQ/hop.git/ master gradle check
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.914 secs
```

For some reason the 2nd time around it Gradle believes that the `:test` task is up-to-date and there's nothing to do.

**Comment by artembilan** [comment]
Since you don't have a `clean` task there and the first is `BUILD SUCCESSFUL`, the Gradle treats everything as up-to-date and, therefore, by pass all the task in the second call.

If you would be like to have a fresh call for the second one as the first one even if that is `BUILD SUCCESSFUL`, you should add `clean` task to the command:

```
λ ~/Development/RabbitMQ/hop.git/ master gradle clean check
```

**Comment by michaelklishin** [comment]
@artembilan my point is that `gradle check` is something often need to run a few times in a row and I can't. This is unlike pretty much any other client test suite I can think of :)

**Comment by artembilan** [comment]
Fully unclear what you mean.
That is just an `UP-TO-DATE` Gradle feature. And `check` task doesn't have anything specific on the matter.
The first run from my side:
```
d:\SpringIO\rabbitmq\hop>gradlew check
Starting a Gradle Daemon (subsequent builds will be faster)
:compileJava
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
:check

BUILD SUCCESSFUL

Total time: 14.703 secs
```
And now I don't touch any file in the project and run it again:
```
d:\SpringIO\rabbitmq\hop>gradlew check
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.823 secs
```
Now I go to the `ClientSpec` , add `cf.port = 5672` , save the file and run again:
```
d:\SpringIO\rabbitmq\hop>gradlew check
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
:check

BUILD SUCCESSFUL

Total time: 8.292 secs
```

Am I missing something ?

**Comment by michaelklishin** [comment]
How do you run `gradle check` 100 times in a row without changing any specs or source files? I need this to reproduce a rare race condition in the server, for example. In rabbit-hole or Ruby HTTP API client or Langohr you just combine `for` with a `make` or similar. Here I need to use `gradle clean check` which will clean the repo 100 times for no good reason.

**Comment by michaelklishin** [comment]
In other words, memoization of results is a great feature for a build tool to have. Except for one case: when a task has side effects (such as running integration tests that involve communication over the network).

**Comment by artembilan** [comment]
Got it!
Thank you for such a good explanation :smile: 

Try the `cleanTest` task:
```
d:\SpringIO\rabbitmq\hop>gradlew cleanTest check
:cleanTest
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test
:check

BUILD SUCCESSFUL

Total time: 7.379 secs
```
Pay attention how everything is `UP-TO-DATE`, but not `test` and `check`.
https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_tasks and look for `cleanTaskName` description

**Comment by michaelklishin** [comment]
Alright, so with `cleanTest` I can do

```
for i in {1..50}; do gradle cleanTest check; done
```

and it turns out to be about `2.5` seconds faster per iteration compared to `clean check`.

I guess I'm swimming upstream here and should just accept the above as good enough (which it is).

Thank you, @artembilan.
