### ISSUE TITLE
Version Info in the README Needs Updating

### ISSUE THREAD

**Issue by garyrussell** [rabbitmq/hop#96]

**Comment by garyrussell** [comment]
Sorry @michaelklishin I just noticed that the maven repo in the README points to the spring repo; this is fine, but the jar is in maven central too so probably not necessary to mention the spring repo, unless you want to point them to the `.../milestone` and/or `.../snapshot` spring repos.

**Comment by michaelklishin** [comment]
@garyrussell OK, I will mention both and recommend Maven Central by default. Cheers.
