### ISSUE TITLE
Connection timeout in Client API

### ISSUE THREAD

**Issue by majidazimi** [rabbitmq/hop#99]
As far as I can see in the client API, even though `HttpClientBuilder` is used inside `Client.getRequestFactory` and it supports connection timeouts, it is not exposed as part of constructor. I'm not able to find any other way to set timeout. This is somehow useful in cluster environment when we want to bring down one node for maintenance. Client should timeout fairly fast so I can re-issue the command to some other node in the cluster.

**Comment by acogoluegnes** [comment]
Which `HttpClientBuilder` setting are you referring to?

There are way too many different settings in `HttpClientBuilder` to provide an constructor argument for. It'd be better to provide a way to customize the `HttpClientBuilder`, e.g. with a callback or a protected method (I'd prefer the callback).

WDYT @artembilan @michaelklishin ?

**Comment by michaelklishin** [comment]
It's a good idea to expose timeouts.

**Comment by majidazimi** [comment]
@acogoluegnes This [one ](https://github.com/rabbitmq/hop/blob/master/src/main/java/com/rabbitmq/http/client/Client.java#L630)inside [`getRequestFactory`](https://github.com/rabbitmq/hop/blob/master/src/main/java/com/rabbitmq/http/client/Client.java#L617)
Accepting `Properties` or some form of Key/Value configuration would be also fine.

**Comment by michaelklishin** [comment]
I'd rather add a way to customise the builder with a function (SMI?)

**Comment by majidazimi** [comment]
@michaelklishin What if the underlying HTTP client is changed? Then user would need to modify the code to work with new builder. Correct me if I'm wrong.

**Comment by michaelklishin** [comment]
@majidazimi the chance of that is about 0. What if the underlying client is changed in a way that we can no longer support some of the properties? Same story, really.

**Comment by michaelklishin** [comment]
The upside of using a function for configuration is that any new setting in the underlying client is immediately available to the users without us having to whitelist/propagate options. And there are *many* options to configure in Apache HTTP client.

**Comment by majidazimi** [comment]
Great. Thanks for supporting...

**Comment by artembilan** [comment]
How about just request an `HttpClient` instance configured externally?
Although function configuration variant sounds good, too.

**Comment by michaelklishin** [comment]
Accepting arbitrary HTTP clients means we must ensure that the user has provided a sufficiently configured instance, which is not something I'd like to maintain.

**Comment by michaelklishin** [comment]
@artembilan so what if we introduce a Single Method Interface for JDK 6 in 1.1.0, then release it and replace it with a lambda-based configurator and require JDK 8 for master/2.0?

**Comment by artembilan** [comment]
Well, let's take a look at the code one more time!
```
  final HttpClientBuilder bldr = HttpClientBuilder.create().
        setDefaultCredentialsProvider(getCredentialsProvider(url, theUser, thePassword));
    bldr.setDefaultHeaders(Arrays.asList(new BasicHeader(HttpHeaders.CONTENT_TYPE, "application/json")));
    if (sslConnectionSocketFactory != null) {
      bldr.setSSLSocketFactory(sslConnectionSocketFactory);
    }
    if (sslContext != null) {
      bldr.setSslcontext(sslContext);
    }

    HttpClient httpClient = bldr.build();
```

So, maximum what we do here regarding "sufficient configuration" is `setDefaultHeaders()`. 
Everything rest really comes from end-user: `url`, `login`, `password`, `SSL` etc..

I might agree that we would prefer to have those `setDefaultHeaders()` on the arbitrary `httpClient`, but even with function configurer we will suffer the same problem, when end-user decide to call `setDefaultHeaders()` on the builder from callback:
```
client.setHttpClientConfigurer(builder -> builder.setDefaultHeaders(...));
```

And therefore requesting external `HttpClient` instance or configure our internal `builder` on the matter are fully similar ways.
Isn't it?

The `HttpClient` variant would meet our Spring XML configuration easily, though...

**Comment by michaelklishin** [comment]
yes but an accidental override seems much less likely to me than forgetting to set a critically important value

**Comment by artembilan** [comment]
OK. Fine with me that way.
And "yes" for your changes suggestion: extra interface for `1.1.x` and `Function` for `2.0`.

**Comment by michaelklishin** [comment]
@majidazimi I submitted #100, WDYT?

**Comment by majidazimi** [comment]
@michaelklishin Awesome. Everything looks as expected.
